import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import SectionTitle from '../components/common/SectionTitle';
import CategoryList from '../components/store/categories/CategoryList';
import ProductsList from '../components/store/products/ProductsList';
import { AppContext } from '../context/AppContextProvider';
import { CategoryType } from '../types/Category';
import { ProductType } from '../types/Product';
import { fetchCategories } from './../api/categories';
import { fetchProducts, fetchProductsByCat } from './../api/products';
import FiltersContainer from './../components/store/Filters/FiltersContainer';

interface HomePageProps {
	products: ProductType[];
	categories: CategoryType[];
}

const Home: NextPage<HomePageProps> = ({ products, categories }) => {
	const [productsState, setProductsState] = useState<ProductType[]>(
		() => products
	);
	const [filteredProducts, setFilteredProducts] = useState<ProductType[]>(
		() => products
	);
	const { currentCategory } = useContext(AppContext);

	useEffect(() => {
		if (!currentCategory) return;
		fetchCategoryProducts(currentCategory?.id);
	}, [currentCategory]);

	useEffect(() => {
		setFilteredProducts([...productsState]);
		console.log('cateProState', productsState);
	}, [productsState]);
	const fetchCategoryProducts = async (catId: number) => {
		const categoryProducts = await fetchProductsByCat(catId);
		console.log('catePro', categoryProducts);
		setProductsState([...categoryProducts]);
	};
	return (
		<>
			<Head>
				<title>Edfa3ly E-commerce</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SectionTitle
				title="Edfa3ly Store"
				description="Choose from our different products and categories"
			/>
			<div className="container mx-auto px-3">
				<CategoryList categories={categories} />
				<section className="grid grid-cols-3 gap-8 my-6">
					{/* filters here */}
					<FiltersContainer categories={categories} />
					<ProductsList
						setProducts={setFilteredProducts}
						products={filteredProducts}
						originalProducts={products}
					/>
				</section>
			</div>
		</>
	);
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx: any) => {
	const categories = await fetchCategories();
	const products = await fetchProducts();
	return {
		props: {
			categories,
			products,
		},
	};
};
